# Generated by Django 3.1.2 on 2020-10-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('contant', models.TextField(max_length=3000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
