# Generated by Django 3.1.2 on 2020-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
