# Generated by Django 3.1.2 on 2020-10-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201004_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Email',
        ),
    ]
