# Generated by Django 3.1.2 on 2020-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
