# Generated by Django 3.1.2 on 2020-10-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='posts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='contant',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
