# Generated by Django 3.1.2 on 2020-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201004_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISTED', 'PUBLISTED')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
