# Generated by Django 3.1.2 on 2020-10-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISTED', 'PUBLISTED')], default='DRAFT', max_length=20),
        ),
    ]
